<?php

namespace Balsama\BostonRecords;

use Exception;

class Mapper
{
    public static function getOrdered(array $values, array $order)
    {
        if (count($values) < count($order)) {
            throw new Exception("Number of values is less than the number of defined sort orders.");
        }

        $sorted = [];
        foreach ($order as $key => $index) {
            $sorted[$key] = $values[$index];
        }
        return $sorted;
    }

    public const CITATION_2021 = [
        'issuing_agency' => 0,
        'agency_code' => 1,
        'officerid' => 2,
        'event_date_raw' => 3,
        'viol_type' => 7,
        'citation_number' => 8,
        'citation_type' => 9,
        'offense' => 10,
        'offense_description' => 11,
        'disposition' => 12,
        'disposition_desc' => 13,
        'location_name' => 14,
        'searched' => 15,
        'crash' => 16,
        'court_code' => 17,
        'race' => 18,
        'gender' => 19,
        'year_of_birth' => 20,
        'lic_state' => 21,
        'lic_class' => 22,
        'cdl' => 23,
        'platetype' => 24,
        'vhc_state' => 25,
        'vhc_year' => 26,
        'make_model' => 27,
        'commercial' => 28,
        'vhc_color' => 29,
        'sixteen_pass' => 30,
        'hazmat' => 31,
        'amount' => 32,
        'hearing_requested' => 34,
        'speed' => 35,
        'posted_speed' => 36,
        'viol_speed' => 37,
        'posted' => 39,
        'radar' => 40,
        'clocked' => 41,
        'time_hh_raw' => 4,
        'time_mm_raw' => 5,
        'am_pm_raw' => 6,
    ];
    public const CITATION_2024 = [
        'issuing_agency' => 0,
        'agency_code' => 1,
        'officerid' => 2,
        'event_date_raw' => 3,
        'viol_type' => 8,
        'citation_number' => 9,
        'citation_type' => 10,
        'offense' => 11,
        'offense_description' => 12,
        'disposition' => 13,
        'disposition_desc' => 14,
        'location_name' => 16,
        'searched' => 17,
        'crash' => 18,
        'court_code' => 19,
        'race' => 20,
        'gender' => 21,
        'year_of_birth' => 22,
        'lic_state' => 23,
        'lic_class' => 24,
        'cdl' => 25,
        'platetype' => 26,
        'vhc_state' => 27,
        'vhc_year' => 28,
        'make_model' => 29,
        'commercial' => 30,
        'vhc_color' => 31,
        'sixteen_pass' => 32,
        'hazmat' => 33,
        'amount' => 34,
        'hearing_requested' => 35,
        'speed' => 36,
        'posted_speed' => 37,
        'viol_speed' => 38,
        'posted' => 39,
        'radar' => 40,
        'clocked' => 41,
        'time_hh_raw' => 4,
        'time_mm_raw' => 5,
        'am_pm_raw' => 6,
    ];
    public const TICKET_2023 = [
        'ticket_number' => 0,
        'ticket_issue_date' => 1,
        'ticket_issue_time' => 2,
        'issuing_agency' => 3,
        'violation_code' => 4,
        'violation_desc_long' => 5,
        'route' => 6,
        'location' => 7,
        'issuing_office_badge_number' => 8,
        'vehicle_body_style' => 9,
        'vehicle_color_desc' => 10,
        'vehicle_make' => 11,
        'plate_type' => 12,
        'rp_plate_state' => 13,
        'rp_plate' => 14,
        'fine_amount' => 15,
        'street_no' => 16,
        'street_direction' => 17,
        'street_name' => 18,
        'street_suffix' => 19,
        'tick_disposition' => 20,
    ];

    public const CITATION_FROM_DB = [
        'issuing_agency' => 0,
        'agency_code' => 1,
        'officerid' => 2,
        'event_date_raw' => 3,
        'viol_type' => 4,
        'citation_number' => 5,
        'citation_type' => 6,
        'offense' => 7,
        'offense_description' => 8,
        'disposition' => 9,
        'disposition_desc' => 10,
        'location_name' => 11,
        'searched' => 12,
        'crash' => 13,
        'court_code' => 14,
        'race' => 15,
        'gender' => 16,
        'year_of_birth' => 17,
        'lic_state' => 18,
        'lic_class' => 19,
        'cdl' => 20,
        'platetype' => 21,
        'vhc_state' => 22,
        'vhc_year' => 23,
        'make_model' => 24,
        'commercial' => 25,
        'vhc_color' => 26,
        'sixteen_pass' => 27,
        'hazmat' => 28,
        'amount' => 29,
        'hearing_requested' => 30,
        'speed' => 31,
        'posted_speed' => 32,
        'viol_speed' => 33,
        'posted' => 34,
        'radar' => 35,
        'clocked' => 36,
        'time_hh_raw' => 37,
        'time_mm_raw' => 38,
        'am_pm_raw' => 39,
    ];
}
