name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      with:
        php-version: 8.2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        php-version: 8.2
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      with:
        php-version: 8.2
      run: composer install --prefer-dist --no-progress

    - name: Lint
      with:
        php-version: 8.2
      run: composer run-script cs

    - name: Run test suite
      with:
        php-version: 8.2
      run: composer run-script test
